spring:
  datasource:
    username: root
    password: theday1012
    url: jdbc:mysql://localhost:3306/online_chat?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: online_chat_server.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml